export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const SEND_MESSAGES_SUCCESS = "SEND_MESSAGES_SUCCESS"

export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_SERVERS_SUCCESS = "GET_SERVERS_SUCCESS"