// Message
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"

// User
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ID = "GET_USER_ID"

// Server
export const GET_SERVERS_SUCCESS = "GET_SERVERS_SUCCESS"
export const CHANGE_CURRENT_SERVER = "CHANGE_CURRENT_SERVER"